### ISSUE TITLE
FileNotFoundError in the normal inference

### ISSUE THREAD

**Issue by blueyo0** [wasserth/TotalSegmentator#6] opened 2022-08-17 12:44 UTC
Hi, the FileNotFoundError is raised when I infer the FLARE22 image with normal mode (the fast mode works smoothly). Seems like some intermediate files are failed to save, do you have any ideas of this issue? 

Here is the command I used:
```
TotalSegmentator -i FLARE22/imagesTr/FLARE22_Tr_0039_0000.nii.gz -o total_pred/FLARE22/FLARE22_Tr_0039_0000_normal
```
Here is the log:
```
Resampling...
Predicting part 0 of 5 ...
Traceback (most recent call last):
  File "xxx/anaconda3/envs/totalseg/bin/TotalSegmentator", line 122, in <module>
    main()
  File "xxx/anaconda3/envs/totalseg/bin/TotalSegmentator", line 102, in main
    seg = nnUNet_predict_image(args.input, args.output, task_id, model="3d_fullres", folds=folds,
  File "xxx/anaconda3/envs/totalseg/lib/python3.9/site-packages/totalsegmentator/nnunet.py", line 154, in nnUNet_predict_image
    (tmp_dir / "s01.nii.gz").rename(tmp_dir / "parts" / f"s01_{tid}.nii.gz")
  File "xxx/anaconda3/envs/totalseg/lib/python3.9/pathlib.py", line 1382, in rename
    self._accessor.rename(self, target)
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/partial_test/FLARE22/imagesTr/nnunet_tmp_IOZ1UFCG/s01.nii.gz' -> 'xxx/partial_test/FLARE22/imagesTr/nnunet_tmp_IOZ1UFCG/parts/s01_251.nii.gz'
```
The test file can be downloaded from https://drive.google.com/file/d/1URovTKT_icuMNeNmMvHOfr4SW9YBz-pK/view?usp=sharing

**Comment by wasserth** [comment] 2022-08-17 13:53
The problem is related to this issue: https://github.com/SimpleITK/SimpleITK/issues/1433
You can see the error message by turning on the verbose mode in TotalSegmentator using the flag `-v`.
You can solve it by using an older version of SimpleITK:
```
pip install SimpleITK==2.0.2
```
Unfortunately SimpleITK did not publish a fix for this yet.

**Comment by CedarYang** [comment] 2022-08-18 08:29
i run pip install SimpleITK==2.0.2;but the same bug: 'D:\\Code\\TotalSegmentator\\nnunet_tmp_MKQI\\s01.nii.gz' -> 'D:\\Code\\TotalSegmentator\\nnunet_tmp_MKQI\\parts\\s01_251.nii.gz' 
i set      num_threads_preprocessing = 0
             num_threads_nifti_save = 1

**Comment by wasserth** [comment] 2022-08-18 09:37
Could you run it again with the option `-v` and post the complete standard output of the command as well as the complete error message?

**Comment by CedarYang** [comment] 2022-08-19 03:53
i run it again with option -v,i run the ,\TotalSegmentator.py in win10 and here is the com:
(seq) D:\Code\TotalSegmentator>python TotalSegmentator.py -i D:\Code\TotalSegmentator\ct.nii.gz -o segmentations -v
Resampling...
  from shape (294, 192, 179) to shape (294, 192, 179)
Predicting part 0 of 5 ...
using model stored in  C:\Users\YangXuesong\.totalsegmentator\nnunet\results\nnUNet\3d_fullres\Task251_TotalSegmentator_part1_organs_1139subj\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['s01']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, [0]
using the following model files:  ['C:\\Users\\YangXuesong\\.totalsegmentator\\nnunet\\results\\nnUNet\\3d_fullres\\Task251_TotalSegmentator_part1_organs_1139subj\\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1\\fold_0\\model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
inference done. Now waiting for the segmentation export to finish...
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the output folder of the model first!
The folder you need to run this in is C:\Users\YangXuesong\.totalsegmentator\nnunet\results\nnUNet\3d_fullres\Task251_TotalSegmentator_part1_organs_1139subj\nnUNetTrainerV2_ep4000_nomirror__nnUNetPlansv2.1
Traceback (most recent call last):
  File "TotalSegmentator.py", line 123, in <module>
    main()
  File "TotalSegmentator.py", line 103, in main
    seg = nnUNet_predict_image(args.input, args.output, task_id, model="3d_fullres", folds=folds,
  File "D:\Code\TotalSegmentator\totalsegmentator\nnunet.py", line 156, in nnUNet_predict_image
    (tmp_dir / "s01.nii.gz").rename(tmp_dir / "parts" / f"s01_{tid}.nii.gz")
  File "D:\ProgramData\Anaconda3\envs\seq\lib\pathlib.py", line 1359, in rename
    self._accessor.rename(self, target)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\Code\\TotalSegmentator\\nnunet_tmp_4KQZ\\s01.nii.gz' -> 'D:\\Code\\TotalSegmentator\\nnunet_tmp_4KQZ\\parts\\s01_251.nii.gz'

**Comment by wasserth** [comment] 2022-08-19 06:49
Unfortunately TotalSegmentator does not work on Windows. You have to use Linux. Or you can try our online tool: https://totalsegmentator.com/

**Comment by CedarYang** [comment] 2022-08-19 07:25
ok，i konw the BUG，its the preprocess_multithreaded，Because win10 does not support multithreading well。i use this 
“if 'win' in sys.platform:
    # fix for pickling errors on Windows platforms
    import pathos
    Process = pathos.helpers.mp.Process
    Queue = pathos.helpers.mp.Queue”
put it into nnunet\inference\predict.py.it works.
Thank you for your work. It's very helpful to be me

**Comment by rbumm** [comment] 2022-09-01 11:12
> ok，i konw the BUG，its the preprocess\_multithreaded，Because win10 does not support multithreading well。i use this  
> if 'win' in sys.platform:
> 
>     #fix for windows platform
> 
>     import pathos  
>     Process = pathos.helpers.mp.Process  
>     Queue = pathos.helpers.mp.Queue  
>  

@CedarYang  Could you tell me exactly where to put this code in nnunet\\inference\\predict.py ? 

Thank you.

**Comment by rbumm** [comment] 2022-09-01 11:34
Thank you  @CedarYang. Very helpful for Windows users.

**Closed** 2022-09-01 12:33 UTC
